#MODE=PROD docker-compose up
#
# Access using fakeservices.datajoint.io
version: '2.4'
services:
  pharus:
    cpus: 0.50
    mem_limit: 512m
    image: datajoint/pharus:0.8.6
    environment:
      PHARUS_SPEC_PATH: /main/specs/sciviz_specsheet.yaml # for dynamic api spec
      PHARUS_MODE: ${MODE} # DEV | PROD
    env_file: .env
    volumes:
      - ./sciviz_specsheet.yaml:/main/specs/sciviz_specsheet.yaml:ro #copy the spec over to /main/specs/YOUR_SPEC_NAME
    command:
      - sh
      - -c
      - |
        gunicorn --bind 0.0.0.0:$${PHARUS_PORT} --workers=1 pharus.server:app
    # export PHARUS_PRIVATE_KEY=$$(echo $$PHARUS_PRIVATE_KEY | sed 's|\\n|\n|g')
    # otumat watch -f $${PHARUS_SPEC_PATH} -s /tmp/reload.sh -i 5
    # ports:
    # - "5000:5000"
    networks:
      - main
  sci-viz:
    cpus: 2.0
    mem_limit: 4g
    image: datajoint/sci-viz:2.3.3
    platform: linux/amd64
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_DJSCIVIZ_BACKEND_PREFIX=/api
      - DJSCIVIZ_SPEC_PATH=/main/sciviz_specsheet.yaml
      - DJSCIVIZ_MODE= ${MODE} # DEV | PROD
      - NODE_OPTIONS=--max-old-space-size=8000
    volumes:
      - ./sciviz_specsheet.yaml:/main/sciviz_specsheet.yaml:ro
    # ports:
    #   - "3000:3000"
    user: root
    command:
      - sh
      - -c
      - |
        sh sci-viz-hotreload-prod.sh
    networks:
      - main
  fakeservices.datajoint.io:
    image: datajoint/nginx:v0.2.6
    environment:
      - ADD_pharus_TYPE=REST
      - ADD_pharus_ENDPOINT=pharus:5000
      - ADD_pharus_PREFIX=/api
      - ADD_sciviz_TYPE=REST
      - ADD_sciviz_ENDPOINT=sci-viz:3000
      - ADD_sciviz_PREFIX=/
      - HTTPS_PASSTHRU=TRUE
    ports:
      - "443:443"
      - "80:80"
    networks:
      - main
networks:
  main:
