name: build_docker

on:
  push:
    branches:
      - main
      - dev
  #pull_request:
  #  branches:
  #    - main
  #    - dev
  workflow_call:
    secrets:
      DOCKERENV:
        required: true
        description: 'Access to AWS RDS server'

jobs:
  build_docker:
    env:
      JHUB_VER: 1.4.2
      PY_VER: 3.9
      DIST: debian
      WORKFLOW_VERSION: 0.1.0
      REPO_OWNER: bernardosabatinilab
      REPO_NAME: sabatini-datajoint-pipeline
      CONTAINER_USER: anaconda
      DJ_HOST: sabatini-dj-prd01.cluster-cjvmzxer50q5.us-east-1.rds.amazonaws.com
      DJ_USER: jbw25
      DJ_PASS: ${{ secrets.DOCKERENV }}
      DATABASE_PREFIX: sabatini_dj_
      RAW_ROOT_DATA_DIR: ./docker/standard_worker/dist/debian/Inbox
      PROCESSED_ROOT_DATA_DIR: ./docker/standard_worker/dist/debian/Outbox
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: |
             docker-compose -f ./docker/standard_worker/dist/debian/docker-compose-standard_worker.yaml -p sabatini-datajoint-pipeline_standard build

      - name: Clean up Docker Compose
        run: |
         docker-compose -f ./docker/standard_worker/dist/debian/docker-compose-standard_worker.yaml down


